services:
  moodle:
    image: tuchsoft/phpmoodle:latest
    ports:
      - "8080:80"
    entrypoint: ["/bin/sh", "-c", "mkdir -p /var/www/moodledata/ && apache2-foreground"]
    volumes:
      - ./moodle:/var/www/html # Edit here
      - moodle_data:/var/www/moodledata
    depends_on:
      - database

  # --- PostgreSQL Block ---
  database:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: moodle
      POSTGRES_USER: moodle
      POSTGRES_PASSWORD: moodle
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

#  # --- MySQL/MariaDB Block ---
#   database:
#     image: mysql:8
#     restart: unless-stopped
#     environment:
#       MYSQL_ROOT_PASSWORD: moodle
#       MYSQL_DATABASE: moodle
#       MYSQL_USER: moodle
#       MYSQL_PASSWORD: moodle
#     volumes:
#       - db_data:/var/lib/mysql
#     ports:
#       - "3306:3306"
#
#  # --- SQL Server Block ---
#   database:
#     image: mcr.microsoft.com/mssql/server:2022-latest
#     restart: unless-stopped
#     environment:
#       ACCEPT_EULA: Y
#       SA_PASSWORD: "moodle"
#       MSSQL_PID: Express
#     volumes:
#       - db_data:/var/opt/mssql
#     ports:
#       - "1433:1433"
#
#  # --- Oracle Database Block ---
#  database:
#    image: gvenzl/oracle-free:latest
#    container_name: oracle
#    restart: always
#    environment:
#      ORACLE_PASSWORD: "moodle"
#      APP_USER: "moodle"
#      APP_USER_PASSWORD: "moodle"
#      ORACLE_ALLOW_REMOTE: "true"
#    ports:
#      - "1521:1521"
#    volumes:
#      - db_data:/opt/oracle/oradata
#      - ./moodle/lib/dml/oci_native_moodle_package.sql:/container-entrypoint-initdb.d/my-init.sql:ro # Edit here


volumes:
  db_data:
  moodle_data:
